name: weather_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any

  intl_utils: ^2.8.1
  cupertino_icons: ^1.0.2

  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  auto_route: ^6.0.5
  dio: ^5.1.1
  retrofit: ^4.0.1
  flutter_svg: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  auto_route_generator: ^6.0.0
  retrofit_generator: ^6.0.0+1
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
